# Generated by Django 5.2.5 on 2025-08-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления:')),
                ('location', models.CharField(blank=True, help_text='Укажите место выполнения привычки', max_length=255, null=True, verbose_name='Место:')),
                ('time', models.TimeField(help_text='Укажите время выполнения привычки', verbose_name='Время:')),
                ('description', models.TextField(help_text='Укажите действие, которое представляет собой привычка', verbose_name='Действие:')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Привычка, которую можно привязать к выполнению полезной привычки', verbose_name='Признак приятной привычки:')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Периодичность выполнения привычки (в днях)', verbose_name='Периодичность:')),
                ('reward', models.CharField(blank=True, help_text='Чем пользователь должен себя вознаградить после выполнения', max_length=255, null=True, verbose_name='Вознаграждение:')),
                ('time_to_complete', models.PositiveSmallIntegerField(blank=True, help_text='Время, которое предположительно потратит пользователь на выполнение привычки (в секундах)', null=True, verbose_name='Время на выполнение:')),
                ('is_public', models.BooleanField(default=False, help_text='Привычки можно публиковать в общий доступ', verbose_name='Признак публичности:')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите пользователя, создавшего привычку', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_habits', to=settings.AUTH_USER_MODEL, verbose_name='Владелец:')),
                ('related_pleasant_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, которая связана с полезной привычкой', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habits.habits', verbose_name='Связанная приятная привычка:')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['time', 'description'],
            },
        ),
    ]
