# Generated by Django 5.2.5 on 2025-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habits_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='time_to_complete',
            field=models.PositiveSmallIntegerField(help_text='Время, которое предположительно потратит пользователь на выполнение привычки (в секундах)', verbose_name='Время на выполнение:'),
        ),
    ]
