# Generated by Django 5.2.5 on 2025-08-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления:')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Укажите ChatID пользователя приложения в Telegram (куда шлём сообщения)', max_length=100, null=True, unique=True, verbose_name='Telegram ChatID:')),
                ('telegram_user_id', models.CharField(blank=True, help_text='Укажите UserID пользователя приложения в Telegram (опционально)', max_length=100, null=True, verbose_name='Telegram UserID:')),
                ('app_user', models.OneToOneField(help_text='Укажите пользователя приложения', on_delete=django.db.models.deletion.CASCADE, related_name='owned_telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь приложения:')),
            ],
            options={
                'verbose_name': 'Телеграм-профиль',
                'verbose_name_plural': 'Телеграм-профили',
                'ordering': ['app_user'],
            },
        ),
    ]
